config/routes.rb
Rails.application.routes.draw do

devise_for :users

resources :users

get 'welcome/index'

get 'welcome/about'

root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :fname, :lname, :age, :gender, :height, :weight, :physical_activity, presence: true

    def total_cal

      formula_female = (((weight * 4.35) + (height * 4.7)) - (age * 4.7)) + 655
      formula_male = (((weight * 6.23) + (height * 12.7)) - (age * 6.8)) + 66

      if gender == "female" && physical_activity == "none"
        @total_cal = (formula_female * 1.2).to_d
      elsif gender == "female" && physical_activity == "light"
        @total_cal = (formula_female * 1.375).to_d
      elsif gender == "female" && physical_activity == "moderate"
        @total_cal = (formula_female * 1.55).to_d
      elsif gender == "female" && physical_activity == "active"
        @total_cal = (formula_female * 1.725).to_d

      elsif gender == "male" && physical_activity == "none"
        @total_cal = (formula_male * 1.2).to_d
      elsif gender == "male" && physical_activity == "light"
        @total_cal = (formula_male * 1.375).to_d
      elsif gender == "male" && physical_activity == "moderate"
        @total_cal = (formula_male * 1.55).to_d
      else gender == "male" && physical_activity == "active"
        @total_cal = (formula_male * 1.725).to_d
      end
      @total_cal
   end

   def total_carbs
     tot_carb = @total_cal * 0.5
     self.update_attributes(:carb => tot_carb)
     carb
   end

   def total_proteins
     tot_prot = @total_cal * 0.2
     self.update_attributes(:protein => tot_prot)
     protein
   end

   def total_fats
     tot_fat = @total_cal * 0.3
     self.update_attributes(:fat => tot_fat)
     fat
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me, :fname, :lname, :age, :gender, :gender_male, :gender_female, :weight, :height, :physical_activity, :physical_activity_mod, :physical_activity_none, :physical_activity_light]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
   @user = User.find(params[:id])
   @user.assign_attributes(user_params)
   if @user.save
     flash[:notice] = "Profile was saved."
     redirect_to @user
   else
     flash.now[:alert] = "There was an error saving your profile. Please try again."
     render :edit
   end
  end

  private

  def user_params
    params.require(:user).permit(:fname, :lname, :age, :gender, :height, :weight, :physical_activity)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <div class="background">
      <%= image_tag("nutri2.jpg") %>
    <div class="container">
    <title>NutriLoop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <ul class="nav nav-tabs">
        <div class="pull-right user-info">
          <%= link_to "Home", root_path %>   <%= link_to "About", welcome_about_path %>
         <% if user_signed_in? %>
         <%= link_to "Profile", current_user, :class => 'navbar-link' %>
         <%= link_to 'Settings', edit_user_registration_path, :class => 'navbar-link' %>  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
             <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %>
             <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
     </ul>
    <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
      </div>
      <% end %>
    </div>
      <%= yield %>
    </div>
  </div>
</div>
  </body>
</html>

app/views/users/edit.html.erb
<div class="row">
  <h2>Please fill out the information below in order for you to track your daily nutrients intake.</h2>

  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :fname, "First Name" %>
      <%= f.text_field :fname, class: 'form-control', placeholder: "Enter first name" %>
    </div>
    <div class="form-group">
      <%= f.label :lname, "Last Name" %>
      <%= f.text_field :lname, class: 'form-control', placeholder: "Enter last name" %>
    </div>
    <div class="form-group">
      <%= f.label :age %>
      <%= f.number_field :age, class: 'form-control', placeholder: "Enter your age" %>
    </div>
    <div class="form-group">
      <%= f.label :gender, "Gender" %> <br>
      <%= f.radio_button :gender, "male" %>
      <%= f.label :gender_male, "Male" %> &nbsp;
      <%= f.radio_button :gender, "female" %>
      <%= f.label :gender_female, "Female" %>
    </div>
    <div class="form-group">
      <%= f.label :height, "Height (in.)" %>
      <%= f.text_field :height, class: 'form-control', placeholder: "Enter your height" %>
    </div>
    <div class="form-group">
      <%= f.label :weight, "Weight (lbs.)" %>
      <%= f.text_field :weight, class: 'form-control', placeholder: "Enter your weight" %>
    </div>
    <div class="form-group">
      <%= f.label :physical_activity %> <br>
      <%= f.radio_button :physical_activity, "none" %>
      <%= f.label :physical_activity_none, "None" %> &nbsp;
      <%= f.radio_button :physical_activity, "light" %>
      <%= f.label :physical_activity_light, "Light (1 - 2 days/week)" %> &nbsp;
      <%= f.radio_button :physical_activity, "moderate" %>
      <%= f.label :physical_activity_mod, "Moderate (3 -5 days/week)" %> &nbsp;
      <%= f.radio_button :physical_activity, "active" %>
      <%= f.label :physical_activity_very_active, "Very active (Daily)" %>
    </div>

    <div class="form-group">
      <%= f.submit "Track", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="row">
  <h1>Welcome!</h1>
  <h4>In order to track your daily nutrients intake, click Register.</h4>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="row">
   <div class="pull-right @user-info"> <br>
     <%= link_to "Edit Profile", edit_user_path(@user), class: 'btn btn-success' %>
   </div>
   <h1>Hello <%= @user.fname %>!</h1>
</div>

<div class="row">
  <h4> Your total daily calories intake: <%= @user.total_cal %> calories </h4>
  <p> Total Carbohydrates : <%= @user.total_carbs %> calories </p>
  <p> Total Proteins : <%= @user.total_proteins %> calories </p>
  <p> Total Fats : <%= @user.total_fats %> calories </p>
</div>

<br>

<div class="graph">
  <h3>Macronutrients/calories</h3>
  <%= bar_chart({"Carbohydrates" => @user.carb, "Proteins" => @user.protein, "Fats" => @user.fat}) %>
</div>

app/views/welcome/about.html.erb
<div class="container">
  <div class="title">
    <h1>NutriLoop</h1>
    <p>Application that helps you be the healthiest version of you! <br>
    We calculate your basal metabolic rate based on your age, gender, weight, height and physical activity. 
    </p>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="title">
    <h1>NutriLoop</h1>
    <h4>Your Daily Nutrients Diary</h4>
    </br>
    <h1>Calculate, track, eat!</h1>
  </div>
</div>